<p style="font-family: Arial; font-size:3em;color:black;"> Session 4 - Lab Exercise 7</p>

We will use the titanic dataset from Kaggle (https://www.kaggle.com/). This is a well-known dataset and we will use it for classification- if the passenger survived or passed away.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
training_DF = pd.read_csv('titanic_dataset_GBC.csv')

In [3]:
training_DF['Age'].fillna(training_DF['Age'].mean(), inplace=True)

In [4]:
training_DF.drop('Cabin',axis=1,inplace=True)

In [5]:
training_DF.dropna(inplace=True)

In [6]:
sex = pd.get_dummies(training_DF['Sex'])
embark = pd.get_dummies(training_DF['Embarked'])

In [7]:
training_DF.drop(['Sex','Embarked','Name','Ticket'],axis=1,inplace=True)

In [8]:
training_DF = pd.concat([training_DF,sex,embark],axis=1)

In [9]:
training_DF.drop(['female','C'],axis=1,inplace=True)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(training_DF.drop('Survived',axis=1), 
                                                    training_DF['Survived'], test_size=0.30, 
                                                    random_state=101)

In [14]:
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)

In [33]:
# let's explore SGDClassifier parameters

'''
SGDClassifier(
    loss='hinge',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)
'''

# Let's form SGD models with variation in paameters loss and alpha
    # loss: 'hinge', 'log', and 'modified_huber'
    # alpha: 0.0001 and 0.001
    # explain and dicuss your findings
    
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

def sgdclassifier(X_train, X_test, y_train, y_test):
    losses = ['hinge', 'log_loss', 'modified_huber']
    alphas = [0.0001, 0.001]
    
    for loss in losses:
        for alpha in alphas:
            model = SGDClassifier(loss=loss, alpha=alpha)
            model.fit(X_train, y_train)
            model_predictions = model.predict(X_test)
            print(f"Confusion matrix for model  where loss is {loss} and alpha is {alpha}")
            print(confusion_matrix(y_test,model_predictions))
            print("Accuracy score for model" , accuracy_score(y_test,model_predictions))
            print("Precision score for model" , precision_score(y_test,model_predictions))
            print("Recall score for model" , recall_score(y_test,model_predictions))
            print("F1 score for model" , f1_score(y_test,model_predictions))
            print("-------------------------------------------")
            
sgdclassifier(X_train, X_test, y_train, y_test)

# Findings are that higher the f1 score better the model is and it depends on your data and the application you are using. The results vary with lower alpha and different loss.

Confusion matrix for model  where loss is hinge and alpha is 0.0001
[[69 94]
 [47 57]]
Accuracy score for model 0.47191011235955055
Precision score for model 0.37748344370860926
Recall score for model 0.5480769230769231
F1 score for model 0.4470588235294118
-------------------------------------------
Confusion matrix for model  where loss is hinge and alpha is 0.001
[[162   1]
 [101   3]]
Accuracy score for model 0.6179775280898876
Precision score for model 0.75
Recall score for model 0.028846153846153848
F1 score for model 0.05555555555555555
-------------------------------------------
Confusion matrix for model  where loss is log_loss and alpha is 0.0001
[[ 25 138]
 [ 12  92]]
Accuracy score for model 0.43820224719101125
Precision score for model 0.4
Recall score for model 0.8846153846153846
F1 score for model 0.5508982035928145
-------------------------------------------
Confusion matrix for model  where loss is log_loss and alpha is 0.001
[[112  51]
 [ 52  52]]
Accuracy score for m

/Users/riyagupta/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(
/Users/riyagupta/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(
/Users/riyagupta/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(
/Users/riyagupta/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(
/Users/riyagupta/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(
/Users/riyagupta/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: Undefine