<p style="font-family: Arial; font-size:3em;color:black;"> Session 4 - Lab Exercise 6</p>

Students in this Group:

- Gabriel Okazaki
- Julio Socher
- Kateryna Solonenko
- Mohit Sabharwal
- Riya Gupta
- Vaibhav Saini

In [101]:
# you can download the original Kyphosis dataset from kaggle at https://www.kaggle.com/abbasit/kyphosis-dataset?select=kyphosis.csv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [102]:
Kyphosis_df = pd.read_csv('kyphosis.csv')

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
X = Kyphosis_df.drop('Kyphosis',axis=1)
y = Kyphosis_df['Kyphosis']

In [105]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [106]:
from sklearn.tree import DecisionTreeClassifier

In [107]:
# Selecting the right "parameters/hyperparameters of ML models can significantly affect their performance".
# let's begin exploring those parameters more for a DT model.
'''
DecisionTreeClassifier(
    criterion='gini',
    splitter='best',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features=None,
    random_state=None,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    min_impurity_split=None,
    class_weight=None,
    presort=False,
)
'''
# Let's consider these three parameters: criterion, splitter, min_samples_split
    # for parameters consider two cases 'gini' and 'entropy'
    # for splitter consider two cases 'best' and 'random'
    # for min_samples_split consider two cases 2 and 5
# explain and discuss your findings

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

def test_decision_tree_parameters(X_train, y_train, X_test, y_test):
    criterions = ['gini', 'entropy']
    splitters = ['best', 'random']
    min_samples_splits = [2, 5]

    for criterion in criterions:
        for splitter in splitters:
            for min_samples_split in min_samples_splits:
                clf = DecisionTreeClassifier(criterion=criterion, splitter=splitter, min_samples_split=min_samples_split)
                clf.fit(X_train, y_train)
                predictions = clf.predict(X_test)
                cm = confusion_matrix(y_test, predictions)
                accuracy = accuracy_score(y_test, predictions)
                precision = precision_score(y_test, predictions, pos_label='present')
                recall = recall_score(y_test, predictions, pos_label='present')
                print(f"Accuracy with Criterion: {criterion}, Splitter: {splitter}, Min Samples Split: {min_samples_split}")
                print(f"Confusion Matrix: \n {cm}")
                print(f"Accuracy: {accuracy}")
                print(f"Precision: {precision}")
                print(f"Recall: {recall} \n")
test_decision_tree_parameters(X_train, y_train, X_test, y_test)

Accuracy with Criterion: gini, Splitter: best, Min Samples Split: 2
Confusion Matrix: 
 [[19  2]
 [ 2  2]]
Accuracy: 0.84
Precision: 0.5
Recall: 0.5 

Accuracy with Criterion: gini, Splitter: best, Min Samples Split: 5
Confusion Matrix: 
 [[16  5]
 [ 2  2]]
Accuracy: 0.72
Precision: 0.2857142857142857
Recall: 0.5 

Accuracy with Criterion: gini, Splitter: random, Min Samples Split: 2
Confusion Matrix: 
 [[19  2]
 [ 3  1]]
Accuracy: 0.8
Precision: 0.3333333333333333
Recall: 0.25 

Accuracy with Criterion: gini, Splitter: random, Min Samples Split: 5
Confusion Matrix: 
 [[20  1]
 [ 3  1]]
Accuracy: 0.84
Precision: 0.5
Recall: 0.25 

Accuracy with Criterion: entropy, Splitter: best, Min Samples Split: 2
Confusion Matrix: 
 [[19  2]
 [ 2  2]]
Accuracy: 0.84
Precision: 0.5
Recall: 0.5 

Accuracy with Criterion: entropy, Splitter: best, Min Samples Split: 5
Confusion Matrix: 
 [[16  5]
 [ 2  2]]
Accuracy: 0.72
Precision: 0.2857142857142857
Recall: 0.5 

Accuracy with Criterion: entropy, Spli

In [ ]:
''' 
The conclusion about those results is that the best model is the entropy with a larger split size, but this does not mean anything since
first, we need to understand the problem we are trying to solve. In some scenarios, we can't have a False Positive, and in some cases, we 
can't have a False Negative, so that determination is essential for our decision on which model to use.

Analyzing the raw results of the mixed parameters we have we can see that the entropy with a larger split size is the most accurate and
precise model while using the same model but with a smaller split size gave us the worst precision. The worst accuracies are found in 
both models and for both with the best splitter and a higher number of samples per split. We can infer that the best splitter works with
a smaller split size.
'''