<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 8</p>

Students name in this Group:
- Gabriel Okazaki
- Julio Socher
- Kateryna Solonenko
- Mohit Sabharwal
- Riya Gupta
- Vaibhav Saini

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets

In [2]:
# Import the built-in iris dataset to work with
iris = datasets.load_iris() # the dataset consists of 3 different types of irises' (Setosa, Versicolour, and Virginica) petal and sepal length
print("iris dataset",iris.data[:10,:])
X = iris.data[:, :2] # We only want to use the first two features (Sepal Length, Sepal Width)
y = iris.target # corresponding to 'setosa', 'versicolor', 'virginica
print("iris target",y[:10,])

iris dataset [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
iris target [0 0 0 0 0 0 0 0 0 0]


In [3]:
# Develop a linear Support Vector Machine to classify the irises
# Use GridSearchCV to optimize the model's hyperparameters (C, gamma, kernel)
# Compare the accuracies of the above two models
model = svm.SVC(
    C=1,  # Regularization parameter: smaller values of C allows for larger margin, potentially leading to more misclassifications on training.
          # The margin is refers to the maximum witdh of the boundary that we can draw between the classes.
          # Reference: https://www.baeldung.com/cs/ml-svm-c-parameter
    gamma=0.01,  # Defines how far the influence of a single training examples reaches.
                 # A high gamma value means only the closest points to the decision boundary will carry the weight leading to a smoother boundary.
                 # A low gamma value means even points far away from the decision boundary have a weight leading to a more wiggly boundary
                 # Reference: https://amagash.github.io/pages/exploration/supervised-learning/svm.html
    kernel='rbf',  # Kernel: Function that takes a low dimensional input space and map it to a higher dimension.
                   # Therefore something that is not linearly separable can be turned into a separable problem.
    random_state=1
)

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [6]:
model.fit(X_train,y_train)

SVC(C=1, gamma=0.01, random_state=1)

In [7]:
predictions = model.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_recall_fscore_support

In [21]:
print('Confusion matrix:')
print(confusion_matrix(
    y_test,
    predictions,
))
print(f'Accuracy score: {accuracy_score(y_test, predictions)}')

Confusion matrix:
[[14  0  0]
 [ 8  0 10]
 [ 0  0 13]]
Accuracy score: 0.6


In [10]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

In [11]:
from sklearn.model_selection import GridSearchCV

In [13]:
grid = GridSearchCV(svm.SVC(),param_grid,refit=True,verbose=3)

In [14]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.762 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.810 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.762 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.667 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.524 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.667 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.667 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [15]:
grid.best_params_

{'C': 1, 'gamma': 1, 'kernel': 'rbf'}

In [16]:
grid.best_estimator_

SVC(C=1, gamma=1)

In [17]:
grid_predictions = grid.predict(X_test)

In [20]:
# Thanks to the Grid Search's optimization, we were able to find better hyperparameters for our SVC model, getting a better accuracy score
print('Confusion matrix:')
print(confusion_matrix(
    y_test,
    grid_predictions,
))
print(f'Accuracy score: {accuracy_score(y_test, grid_predictions)}')

Confusion matrix:
[[14  0  0]
 [ 0 11  7]
 [ 0  3 10]]
Accuracy score: 0.7777777777777778
